# Example configuration file for My AI Assistant

model:
  # Model configuration
  model_name: "gpt-4"  # OpenAI model to use
  max_tokens: 2048    # Maximum tokens for completion
  temperature: 0.7    # Creativity level (0.0-1.0)
  top_p: 1.0          # Nucleus sampling parameter
  frequency_penalty: 0.0  # Penalty for token frequency
  presence_penalty: 0.0   # Penalty for token presence

# General settings
debug: false          # Enable debug mode
log_level: "INFO"     # Logging level (DEBUG, INFO, WARNING, ERROR)

# API server settings
api:
  host: "0.0.0.0"     # Host to bind the API server
  port: 8000          # Port for the API server
  reload: true        # Enable auto-reload for development